### ISSUE TITLE
$TM_BUNDLE_SUPPORT and "Pristine Copy"

### ISSUE THREAD

**Issue by jlecour** [rondevera/jslintmate#1]
I've just installed the bundle, following the instructions, but I get this error when I run the lint

```
Could not open file: /Users/jlecour/Library/Application Support/TextMate/Pristine Copy/Bundles/JSLintMate.tmbundle/Support/lib/jslint.js /Users/jlecour/Library/Application Support/TextMate/Bundles/JSLintMate.tmbundle/Support/lib/jslintmate.rb:27:in `read': No such file or directory - /Users/jlecour/Library/Application Support/TextMate/Pristine Copy/Bundles/JSLintMate.tmbundle/VERSION (Errno::ENOENT) from /Users/jlecour/Library/Application Support/TextMate/Bundles/JSLintMate.tmbundle/Support/lib/jslintmate.rb:27:in `version' from /Users/jlecour/Library/Application Support/TextMate/Bundles/JSLintMate.tmbundle/Support/lib/jslintmate.rb:64:in `link_to_jslintmate' from /Users/jlecour/Library/Application Support/TextMate/Bundles/JSLintMate.tmbundle/Support/lib/jslintmate.rb:172
```

I've found that it's an issue with the $TM_BUNDLE_SUPPORT environment variable.
In a shell, `echo $TM_BUNDLE_SUPPORT` returns "~/Library/Application Support/TextMate/Bundles" but inside TextMate it doesn't seem to work the same way.

I don't know if it's a bug, or a misconfiguration on my part, so if somebody has an idea, i'll take it.

Thanks

**Comment by rondevera** [comment]
Thanks for reporting this! Did you install the bundle by downloading the zip, or via `git clone`?

**Comment by jlecour** [comment]
Via the `git clone`

**Comment by rondevera** [comment]
Thanks Jérémy -- could you please give the 1.0.3 release a try?

**Comment by jlecour** [comment]
It's fixed, thanks.

But then I see another issue : #2
