### ISSUE TITLE
TM2 output not in separate window and can't be closed

### ISSUE THREAD

**Issue by stepheneb** [rondevera/jslintmate#11]
I installed the development branch in TM2 and after executing ctrl-L the output is displayed in a pane at the bottom of the TM2 window instead of in a separate window when using in TM1.  This makes the results harder to review and it's not obvious how to close the results pane.

TextMate Version 2.0 (9064)

jslintmate version:

```
$ git log -1
commit 5a26f33c89022df2472c642809b61ee926d60c78
Author: Ron DeVera <hello@rondevera.com>
Date:   Sat Feb 18 00:27:54 2012 -0800

    Mirror readme screenshot dimensions w/GitHub page
```

Screenshot:

![](https://img.skitch.com/20120222-g9qs1k8b64bd7cnah326fe983k.jpg)

**Comment by rondevera** [comment]
Hi Stephen,

I've chatted with the TextMate team about this, and their current solution is for users to use a hidden preference to change how all bundles (not just JSLintMate) are displayed in TextMate 2.

For instructions on how to make TextMate 2 open JSLintMate in a separate window again, please see the [readme](https://github.com/rondevera/jslintmate/tree/development/#readme) and scroll down to the _TextMate 2_ section.

Cheers,
Ron

**Comment by stepheneb** [comment]
Thanks for that tip Ron,

After running this in the Terminal I get the output in a separate window:

```
defaults write com.macromates.TextMate.preview htmlOutputPlacement window
```
