### ISSUE TITLE
Failure - env: bash: No such file or directory

### ISSUE THREAD

**Issue by jgoodall** [rondevera/jslintmate#13]
Using TM Version 2.0 (9064).

Error when trying to run jslintmate: 

Failure running "Run JSLintMate"
env: bash: No such file or directory

It was working before.

**Comment by rondevera** [comment]
Hi John, thanks for reporting this. When you say it was working before, was this before an upgrade of JSLintMate, TextMate, or both? What was the last combination that worked?

Also, did you install JSLintMate just by downloading the zip, or via `git clone`?

Cheers,
Ron

**Comment by jgoodall** [comment]
It wasnt a new version of either, installed from zip.

Somehow my PATH variable in the TextMate preferences had been set to something, resetting that to the following fixed:
/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
