### ISSUE TITLE
Config option todo does not work together with browser option

### ISSUE THREAD

**Issue by tomcode** [rondevera/jslintmate#18]
I just installed jslintmate. Before I had JSLinted some files using http://www.jslint.com.

I used the options :

<code>/*jslint  todo: true, browser: true */</code>

This passes in the online form but throws me an error in Textmate (1 and 2) 'Unexpected todo'

To have it pass I need to separate the statements :

<code>/_jslint browser: true */
/_ todo: true */</code>

I also tried (both using spaces and tabs) :
<code>/*jslint browser: true,
         todo: true */
</code>

**Comment by rondevera** [comment]
Hey Thomas,

The `todo` option was introduced into the 2012-07-13 build of JSLint (commit 6f23c57), while the version of JSLint that's built into JSLintMate is from 2012-03-02.

The next release of JSLintMate will contain the latest version of JSLint, and should solve this. In the meantime, you can download the latest JSLint and configure JSLintMate to use it; see [the JSLintMate docs ("Custom JSLint/JSHint builds" section)](https://github.com/rondevera/jslintmate#custom-jslintjshint-builds) for details.

Cheers,
Ron

**Comment by tomcode** [comment]
Ron,

Thanks for Your detailed response, sorry for replying so late, had the impression I'd already replied.

You're bundle is highly appreciated.

Thomas
