### ISSUE TITLE
Unable to install on sublimeText

### ISSUE THREAD

**Issue by Freyskeyd** [rondevera/jslintmate#22]
Hi,

I'm using sublime text 2 and i want to make this repo works with.

But when i clone this repo in my package folder, nothing is install..
Tmbundle are compatible with ST2, JSlintMate is it?

Thank's!

**Comment by rondevera** [comment]
Hi Simon,

Although some TextMate bundles work across TextMate and Sublime Text, the JSLintMate project only targets TextMate. However, if you're ever interested in working on a fork for Sublime, I'd be really curious to see it in action!

Cheers,
Ron

**Comment by Freyskeyd** [comment]
::
Hey thank's for comment.

I can't make it, i don't know how to make/convert plugin for sublime text..

Maybe one day, if i've some times
