### ISSUE TITLE
undefined method `find' error

### ISSUE THREAD

**Issue by Joan** [rondevera/jslintmate#28]
All run method are giving me this (added ~):

```
~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate/linter/options_files.rb:27:in `first_readable_options_file_path': undefined method `find' for nil:NilClass (NoMethodError) from ~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate/linter.rb:196:in `get_html_output' from ~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:302:in `start!' from ~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:310
```

**Comment by rondevera** [comment]
Hi Joan, could you please let me know which OS X, TextMate, and JSLintMate versions you're using? Thanks!

**Comment by Joan** [comment]
Oh yes of course, sorry.
OS X 10.8.5 / TM 1.5.10 (1631) / JSLM 1.4

**Comment by dcpesses** [comment]
I'm experiencing this same issue as well:

OS X 10.8.5 / TM 1.5.11 (1635) / JSLM 1.4 / Ruby 1.8.7

**Comment by dguzzo** [comment]
hey @Joan @dcpesses et al, I ran into the same problem today, but dug through the code and found what I was doing wrong.

Here is what the standard Linters preference should look like in the Bundle editor:

``` javascript
{   shellVariables = (
        {   name = 'TM_JSLINTMATE_DEFAULT_LINTER';
            value = 'jslint';
        },
        {   name = 'TM_JSLINTMATE_JSLINT_FILE';
            value = '$TM_BUNDLE_SUPPORT/lib/jslint.js';
        },
        {   name = 'TM_JSLINTMATE_JSHINT_FILE';
            value = '$TM_BUNDLE_SUPPORT/lib/jshint.js';
        },
    );
}
```

I wanted to point to a fresh npm install of jshint instead of the stock one that came with the bundle. So I figured I'd do something like this:

``` javascript
{   shellVariables = (
        {   name = 'TM_JSLINTMATE_DEFAULT_LINTER';
            value = 'jslint';
        },
        {   name = 'TM_JSLINTMATE_JSLINT_FILE';
            value = '$TM_BUNDLE_SUPPORT/lib/jslint.js';
        },
        {   name = 'TM_JSLINTMATE_JSHINT_FILE';
            value = '$TM_BUNDLE_SUPPORT/lib/jshint.js';
        },
        {   name = 'TM_JSLINTMATE_JSHINT_NPM';
            value = '/usr/local/lib/node_modules/jshint/src/jshint.js';
        },
    );
}
```

note the addition of `TM_JSLINTMATE_JSHINT_NPM`, which I then used to set the `linter` option in the run command, as such:

```
ruby "$TM_BUNDLE_SUPPORT/lib/jslintmate.rb" \
  --linter=$TM_JSLINTMATE_JSHINT_NPM
```

But this was **completely the wrong approach**; the `linter` setting should be either `jslint` or `jshint`, not any other value. Here's what it should've been:

``` javascript
{   shellVariables = (
        {   name = 'TM_JSLINTMATE_DEFAULT_LINTER';
            value = 'jslint';
        },
        {   name = 'TM_JSLINTMATE_JSLINT_FILE';
            value = '$TM_BUNDLE_SUPPORT/lib/jslint.js';
        },
        {   name = 'TM_JSLINTMATE_JSHINT_FILE';
            value = '/usr/local/lib/node_modules/jshint/src/jshint.js';
        },
    );
}
```

and the corresponding run command:

```
ruby "$TM_BUNDLE_SUPPORT/lib/jslintmate.rb" \
  --linter=jshint
```

That fixed up my error and immediately my jshint output was coming from the npm version, not the stock bundle version.

Hope that helped. I also realize I should probably use a path ENV var to my global node module directory, but this is good for now :)

**Comment by Joan** [comment]
Hm, I changed linter an snippet content with your cde, still have

```
~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate/linter/options_files.rb:27:in `first_readable_options_file_path': undefined method `find' for nil:NilClass (NoMethodError) from ~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate/linter.rb:196:in `get_html_output' from ~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:302:in `start!' from ~/Library/Application Support/TextMate/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:310
```

:/

**Comment by dguzzo** [comment]
Joan, did you try restarting TextMate after making the change? Actually a restart isn't necessary, but you will need to blur the command pane of the Bundle Editor window. (at least in **Version 1.5.11 (1635)**)

Another surefire way to make sure the settings took effect is to close the Bundle Editor window after making the config change.

**Comment by Joan** [comment]
I closed window and restarted TM (updated to 1.5.11), jslint.js works but not jshint.js
I changed `'/usr/local/lib/node_modules/jshint/src/jshint.js'` to `'/$TM_BUNDLE_SUPPORT/lib/jshint.js'`… it works!

**Comment by dguzzo** [comment]
glad it's working for you! I'm curious what the value of `TM_JSLINTMATE_JSHINT_FILE` was set to before, since the value that ended up working for you is the default as far as i know.

**Comment by rondevera** [comment]
Thanks for your help, @dguzzo!

**Comment by dguzzo** [comment]
no prob!
