### ISSUE TITLE
Allow for use of .hintrc files

### ISSUE THREAD

**Issue by tbeseda** [rondevera/jslintmate#3]
Many users have a global l/hinter config file in their home dir, that is in the same format as the README suggests in the commented portion at the top of the file.

`ruby path/to/jslintmate.rb --linter-options-file="~/.hintrc"` would be rad.

**Comment by rondevera** [comment]
Hey Taylor, just to clarify:
- Does a `~/.lintrc` (or `~/.hintrc`) consist of simple YAML like in [jslint_on_rails](https://github.com/psionides/jslint_on_rails/blob/master/lib/jslint/config/jslint.yml), or is it another format/structure?
- I copied one of my existing `jslint.yml` files to `~/.lintrc`, and changed my copy of the JSLintMate bundle to run ruby "$TM_BUNDLE_SUPPORT/lib/jslintmate.rb" --linter-options-file="$HOME/.lintrc"`. This read the config file properly -- note the change in the file's path prefix.

Are you suggesting setting `--linter-options-file` to default to `$HOME/.lintrc` (or `$HOME/.hintrc`)? Do you also have some links/posts from those users who use these filenames?

**Comment by tbeseda** [comment]
`.h/lintrc` files are like the commented Javascript blocks used in the top of each js file, as noted in your README, but applied globally when Linting.
Maybe the linter could look for (and accept as a parameter) these config file types if no YAML options file is provided, and parse them like it would the options at the top of the js file.
A few Vim L/Hinters behave like this (like [the one](https://github.com/wookiehangover/jshint.vim) I use).

**Comment by rondevera** [comment]
Hey Taylor,

Thanks for your comments! The latest build in the `development` branch now reads from `~/.jslintrc` and `~/.jshintrc` by default; these should be YAML files. Feel free to give it a try, and see if that works for you.

This feature will be part of the upcoming v1.2 release. In a future release, JSLintMate will also support JSON in options files, which matches the format that's used atop JS files.

Cheers,
Ron

**Comment by rondevera** [comment]
Hey Taylor,

JSLintMate 1.2 is now available, and as mentioned before, reads from `/.jslintrc` and `~/.jshintrc` by default. These should be YAML files for now, but JSON support is a top priority for the next big release.

There's a new, much simpler system for setting custom paths for your options files -- just open the "Options Files" preferences in the bundle. More info is in the [readme](https://github.com/rondevera/jslintmate/#readme). Don't hesitate to poke me with any questions!

http://rondevera.github.com/jslintmate/

Cheers,
Ron

**Comment by tbeseda** [comment]
Awesome! I have been giving Sublime Text a shot, but may make it back to TM, and I'll be sure to update jslintmate

**Comment by rondevera** [comment]
Hey Taylor,

JSLintMate 1.3 is now available, and adds support for both YAML and JSON options files. The project now includes some [example options files](https://github.com/rondevera/jslintmate/tree/master/Support/config/).

This update should make your options files fully usable with other JSLint/JSHint tools (e.g., automated test suites), and hopefully wraps up this ticket. Let me know if anything's missing!

http://rondevera.github.com/jslintmate/

Cheers,
Ron
