### ISSUE TITLE
Error in Installing JSLintMate for TextMate in Mavericks

### ISSUE THREAD

**Issue by ankur0890** [rondevera/jslintmate#30]
I am trying to install JSLintMate http://rondevera.github.io/jslintmate/ for my text mate. Downloaded the bundle from their website and it suggested that it will get install automatically.

On unzipping it is asking for file encoding format and i am selecting default UTF-8
![screen shot 2014-03-30 at 12 54 29 am](https://cloud.githubusercontent.com/assets/1263424/2559385/2f5948f0-b779-11e3-8a91-c9ebe1d1f90c.png)

But after running the installation bundle I am getting an error

The bundle “JavaScript JSLintMate 1.4.tmbundle” does not contain the required “info.plist” file (or that file is corrupt) and can therefore not be installed.
![screen shot 2014-03-30 at 12 45 05 am](https://cloud.githubusercontent.com/assets/1263424/2559391/5ea363ac-b779-11e3-8156-e1af008de1c4.png)

i am trying to install JSLintMate http://rondevera.github.io/jslintmate/ for my text mate. Downloaded the bundle from their website and it suggested that it will get install automatically.

On unzipping it is asking for file encoding format and i am selecting default UTF-8

enter image description here

But after running the installation bundle I am getting an error

The bundle “JavaScript JSLintMate 1.4.tmbundle” does not contain the required “info.plist” file (or that file is corrupt) and can therefore not be installed.

enter image description here

I searched on the web regarding this but not able to find the solution.

Text-Mate Version: 1.5.11 
OSX: Maverics 10.9 
JSLintMate: 1.4

Is there anything wrong from my side or some additional step is required to make it work.

**Comment by rondevera** [comment]
Hi @ankur0890, I couldn't reproduce this in Mavericks or on other older systems when downloading the zip file. Does it work if you unzip the file with the OS X default instead of The Unarchiver?

**Comment by ankur0890** [comment]
Its running fine when you are running it with default archive utility. Some problem with the unarchiver only. Thanks for your help :)
