### ISSUE TITLE
JSHint version is out-of-date

### ISSUE THREAD

**Issue by jamesarosen** [rondevera/jslintmate#4]
The version included herein does not have support for `"expr"` the setting to allow lines like

```
foo && foo.bar && foo.bar('baz');
```

I replaced the version in `~/Library/Application Support/TextMate/Bundles/JSHintMate.tmbundle/Support` with the latest from [http://jshint.com/jshint.js](http://jshint.com/jshint.js) and it worked fine.

**Comment by rondevera** [comment]
Thanks James; the 1.0.4 release now uses the latest for each lint tool (JSLint 2011-05-06, JSHint 2011-04-16).

**Comment by jamesarosen** [comment]
:+1:
