### ISSUE TITLE
JSHint/JSLint on save

### ISSUE THREAD

**Issue by antris** [rondevera/jslintmate#5]
There is this sentence in the Readme:

"This bundle doesn't run JSLint/JSHint on save because doing so can incur noticeable overhead."

I do not understand what is meant by "overhead" in this. I've used on-save JSLint with the Javascript Tools bundle here: https://github.com/subtleGradient/javascript-tools.tmbundle

It shows a small tooltip notifications if there's warnings or errors. This has been working great for me in the past and I notice all the errors straight away without having to worry about committing non-linted code by accident.

The only downside of Javascript tools is that it does not work with JSHint. So it'd be great if you had the on-save option or explained what is meant by "overhead" in the Readme.

Thanks! :)

**Comment by rondevera** [comment]
Hey antris,

Thanks for your feedback! The JSLint bundles I've tried have two general approaches:
- They prepare a list of errors, then render a tooltip. This is very fast and ideal for lint-on-save, but the UI is inflexible and not interactive.
- They open a TextMate window, pause briefly, then render their results. This is flexible and interactive, but slower (ranging from "a tiny delay" to "productivity-haltingly slow").

I've tried a few bundles that combine these -- they open a new window on save. This was slow with large JS files (read: CPU-hogging overhead), and the frustration adds up quickly if you're saving frequently before fixing all the errors.

To avoid this frustration, JSLintMate avoids bogging down the cmd-S shortcut, and only loads when you're ready.

That said, I can see the workflow you're describing:
1. Cmd-S saves changes, and quietly runs JSLintMate. If there are any errors, a quick tooltip summarizes what's wrong, and tells you to open the full error window (if you need it).
2. Ctrl-L (or ctrl-shift-L) opens the full JSLint/JSHint window, where you can navigate the error list with the keyboard.

Does this sound like what you're looking for?

Cheers,
Ron

**Comment by antris** [comment]
Hey Ron!

Thanks for taking the time to read the issue. You've exactly described my workflow. As I tend to do atomic saves after each change, I usually spot the error without having to get any details. All I need to know is that something is wrong.

Here is a screenshot of what Javascript Tools bundle does:
![Javascript Tools showing a JSLint warning in a tooltip](http://dl.dropbox.com/u/829690/Screen%20shot%202011-06-07%20at%209.04.55.png)

After seeing that, if I don't know what's wrong then I can always go for the full scan with the errors. If there are no errors or warnings, the tooltip never comes up.

I haven't run to any file that is so big that it would cause hogging on Cmd-S with Javascript Tools, even on big projects. Though I can see how I might not have noticed that, because it indeed is not a blocking popup, it just shows up when it's done.

Also, just as an uneducated guess there might be some work to be done optimizing the speed of the non-detailed linting. But for me, this option would work so well, I wouldn't want to work any other way.

**Comment by starzonmyarmz** [comment]
I would find this useful also... same functionality that comes with the TextMate plugin: Javascript Tools (see https://github.com/johnmuhl/javascript-tools-tmbundle/blob/master/Commands/Quick%20Lint.tmCommand).

**Comment by rondevera** [comment]
Hey Anton and Daniel,

Sorry this took a while, but thanks for your feedback and patience! The latest `development` build now contains this feature -- feel free to give it a spin. Unless something comes up during my tests, this'll be part of the v1.2 release that's in progress.

By default, command-S runs JSLint. The latest version of the readme has instructions on how to switch to JSHint.

Let me know if you have any questions or concerns!

Cheers,
Ron

**Comment by antris** [comment]
Incredible, thanks! Will check it as soon as I'm able to :)

**Comment by rondevera** [comment]
Hey Anton and Daniel,

JSLintMate 1.2 is now available, and thanks to your feedback, it now has a quick tooltip-on-save feature! JSLintMate runs your code through JSLint whenever you hit _command-S_. The keyboard shortcut can be changed easily, and you can also switch the default to JSHint; instructions are in the [readme](https://github.com/rondevera/jslintmate/#readme). Enjoy!

http://rondevera.github.com/jslintmate/

Cheers,
Ron
