### ISSUE TITLE
predef in yaml file not observed

### ISSUE THREAD

**Issue by jschilli** [rondevera/jslintmate#7]
I've tried a few different options with defining predef, all valid YAML statements.

predef: 
- AGlobal
- AnotherGlobal

and 

predef: [AGlobal, AnotherGlobal]

debugging shows that they are set on the command line when calling jsc, but jslint doesn't recognize them.

Has anyone had any luck with this?

**Comment by rondevera** [comment]
Hey Jeff,

Thanks for reporting this, and for being patient! I've pushed initial support for the `predef` feature to the `development` branch. I'll be testing it before releasing v1.2, but feel free to try it out early.

Cheers,
Ron

**Comment by rondevera** [comment]
Hey Jeff,

Thanks again for reporting this! JSLintMate 1.2 is now available, and properly supports the `predef` option for listing known globals.

Instructions for using your own custom options are now much simpler, and are covered in the [readme](https://github.com/rondevera/jslintmate/#readme) -- just modify the "Options Files" preferences. Don't hesitate to poke me if you have questions. Enjoy!

http://rondevera.github.com/jslintmate/

Cheers,
Ron
