### ISSUE TITLE
jslintmate doesn't works in TextMate 2.0 alpha

### ISSUE THREAD

**Issue by paulocmoreno** [rondevera/jslintmate#8]
Version: 2.0 (8930).
Bundle installed in Application/Textmate/Contents/SharedSupport/Bundles.

**Comment by paulocmoreno** [comment]
Error message:
/Applications/TextMate.app/Contents/SharedSupport/Bundles/JSLintMate-1.1.tmbundle/Support/lib/jslintmate.rb:65:in `dup': can't dup NilClass (TypeError)
    from /Applications/TextMate.app/Contents/SharedSupport/Bundles/JSLintMate-1.1.tmbundle/Support/lib/jslintmate.rb:65:in`bundle_path'
    from /Applications/TextMate.app/Contents/SharedSupport/Bundles/JSLintMate-1.1.tmbundle/Support/lib/jslintmate.rb:60:in `lib_path'
    from /Applications/TextMate.app/Contents/SharedSupport/Bundles/JSLintMate-1.1.tmbundle/Support/lib/jslintmate/linter.rb:40:in`initialize'
    from /Applications/TextMate.app/Contents/SharedSupport/Bundles/JSLintMate-1.1.tmbundle/Support/lib/jslintmate.rb:118:in `new'
    from /Applications/TextMate.app/Contents/SharedSupport/Bundles/JSLintMate-1.1.tmbundle/Support/lib/jslintmate.rb:118

**Comment by rondevera** [comment]
Thanks Paulo! TextMate 2 support is the top priority for JSLintMate 1.3.

**Comment by rondevera** [comment]
Hey Paulo,

I'm investigating this at the moment -- JSLintMate seems to work smoothly in TextMate 2 when installed in the [recommended location](http://blog.macromates.com/2011/locating-bundles/), `~/Library/Application Support/Avian/Pristine Copy/Bundles/`. Have you tried installing the bundle there manually?

Cheers,
Ron

**Comment by rondevera** [comment]
Digging further, I'm getting a different error when testing against a different codebase:

```
Could not open file: ./Support/lib/jsc.js
/Users/ron/Library/Application Support/Avian/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:46:in `read': No such file or directory - ./VERSION (Errno::ENOENT)
    from /Users/ron/Library/Application Support/Avian/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:46:in `version'
    from /Users/ron/Library/Application Support/Avian/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:133:in `link_to_website'
    from /Users/ron/Library/Application Support/Avian/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate/linter.rb:168:in `get_html_output'
    from /Users/ron/Library/Application Support/Avian/Pristine Copy/Bundles/JavaScript JSLintMate.tmbundle/Support/lib/jslintmate.rb:191
```

This isn't the same error as originally reported, but it shows that there's work to be done. I'm currently testing against TextMate 2.0 (8956).

**Comment by rondevera** [comment]
TextMate 2 seems to have removed the `$TM_BUNDLE_PATH` environment variable, so I've made [a small change](https://github.com/rondevera/jslintmate/commit/f3a6e709742a56da8bc93c8004d9a82dea2d30a1) so that JSLintMate uses `$TM_BUNDLE_SUPPORT` + `..` instead.

Further progress that's specific to TextMate 2 will be done in the [textmate2 branch](https://github.com/rondevera/jslintmate/tree/textmate2).

Cheers,
Ron

**Comment by paulocmoreno** [comment]
@rondevera, I found the information about the new bundle install directory after I created my issue. I move the bundle to this directory, but the problem persists. 

I tested your change in their branch textmate2 and it worked perfectly. Thanks!

**Comment by rondevera** [comment]
TextMate 2 is now officially supported as of [JSLintMate 1.3](http://rondevera.github.com/jslintmate/).
